export {default as dashboard} from "./dashboard.png";
export {default as ChiplAdmin} from "./ChiplAdmin.png";
export {default as fleets} from "./fleets.png";
export {default as stocks} from "./stocks.png";
export {default as live} from "./live.png";
export {default as reportamtek} from "./report.png";
export {default as profilePage} from "./profilePage.png";
export {default as help} from "./help.png";
export {default as Aboutus} from "./About-us.png";
export {default as jerk} from "./line-chart.png";
export {default as location} from "./google-maps.png";
export { default as maintenance } from "./maintenance.webp";
export { default as history } from "./history.webp";