import { SuperAdminnavbar } from "@/src/types/SuperAdmin";
import {
  Aboutus,
  ChiplAdmin,
  dashboard,
  fleets,
  help,
  jerk,
  live,
  location,
  profilePage,
  reportamtek,
  stocks,
} from "@/src/assets/SuperAdmin/Sidebar/Index";
import { camera } from "@/src/assets/SuperAdmin/fleets/offcanvas";

export const navbar: SuperAdminnavbar[] = [
  {
    id: 1,
    icon: dashboard,
    title: "Dashboard",
    path: "/dashboard",
    pagePath: "dashboard",
  },
  {
    id: 2,
    icon: ChiplAdmin,
    title: "Admin",
    path: "/admin",
    pagePath: "admin",
  },
  // {
  //   id: 3,
  //   icon: fleets,
  //   title: "Fleets",
  //   path: "/fleets",
  //   pagePath: "Fleets",
  // },
  {
    id: 4,
    icon: stocks,
    title: "Stocks",
    path: "/stocks",
    pagePath: "Stocks",
  },
  {
    id: 5,
    icon: live,
    title: "Live Data",
    path: "/liveData",
    pagePath: "LiveData",
  },
  // {
  //   id: 10,
  //   icon: jerk,
  //   title: "Jerk",
  //   path: "/SuperAdmin/jerk",
  //   pagePath: "jerk",
  // },
  // {
  //   id: 11,
  //   icon: location,
  //   title: "Location",
  //   path: "/location",
  //   pagePath: "location",
  // },
  // {
  //   id: 13,
  //   icon: camera,
  //   title: "Camera",
  //   path: "/camera",
  //   pagePath: "camera",
  // },
  {
    id: 9,
    icon: reportamtek,
    title: "Report",
    path: "https://24x7healthcare.live/allReport",
    pagePath: "report",
  },
  {
    id: 6,
    icon: profilePage,
    title: "Profile",
    path: "/profile",
    pagePath: "Profile",
  },
  {
    id: 7,
    icon: help,
    title: "Help",
    path: "/help",
    pagePath: "Help",
  },
  {
    id: 8,
    icon: Aboutus,
    title: "About Us",
    path: "/About_Us",
    pagePath: "About_Us",
  },
  // {
  //   id: 9,
  //   icon: Aboutus,
  //   title: "Hams Login",
  //   path: "/hamslogin",
  //   pagePath: "hamslogin",
  // },
];

